version: '3'
services:
  mysql:
    build: .
    platform: linux/amd64
    command: >-
      mysqld
      --character-set-server=utf8mb4
      --sql-mode='TRADITIONAL,NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY'
      --max_connections=10000
    environment:
      - MYSQL_ROOT_PASSWORD = test
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/scripts
    ports:
      - "3306:3306"
volumes:
  mysql_data:
    driver: local
